name: Hello World Yaml
on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Hello-world
        run: echo "Hello-world"
        shell: bash
  goodbye:
    run-on: ubuntu-latest
    steps:
      -  name: Goodbye
         run: echo :goodbye"
         shell: bash      
